Ensure it fails when decryption fails

diff --git a/hooks/environment b/hooks/environment
--- a/hooks/environment
+++ b/hooks/environment
@@ -12,7 +12,17 @@ ejson_exports() {
     $EJSON2ENV_BIN_PATH --key-from-stdin "$BUILDKITE_PLUGIN_EJSON2ENV_EJSON_FILE"
 }
 
-eval "$(ejson_exports)"
+export_secrets() {
+  local export_lines
+  if export_lines="$(ejson_exports)"; then
+    eval "$export_lines"
+  else
+    echo "Failed to export EJSON secrets from $BUILDKITE_PLUGIN_EJSON2ENV_EJSON_FILE"
+    exit 1
+  fi
+}
+
+export_secrets
 
 if [ "${EJSON2ENV_TEST_MODE:-false}" == "true" ]; then
   if [ -n "${EJSON2ENV_TEST_VERIFY_KEY:-}" ]; then
